import type { DiagramNodeDTO, DiagramRelationDTO, DiagramType } from '../../types/diagrams'
import { Button } from '../ui/Button'

interface DiagramQualityModalProps {
  nodes: DiagramNodeDTO[]
  edges: DiagramRelationDTO[]
  diagramType: DiagramType
  isAutoGenerated: boolean
  lastSavedStatus?: string
  onClose: () => void
  onSelectElement: (targetType: 'node' | 'edge', targetId: string) => void
  onAutoLayout: () => void
  onCleanDuplicates: () => void
}

export function DiagramQualityModal({
  nodes,
  edges,
  diagramType,
  isAutoGenerated,
  lastSavedStatus,
  onClose,
  onSelectElement,
  onAutoLayout,
  onCleanDuplicates,
}: DiagramQualityModalProps) {
  const isClass = diagramType === 'CLASS'

  // Calculate isolated nodes
  const connectedNodeIds = new Set<string>()
  edges.forEach(e => {
    connectedNodeIds.add(e.source)
    connectedNodeIds.add(e.target)
  })
  
  const isolatedNodes = nodes.filter(n => n.kind !== 'package' && !connectedNodeIds.has(n.id))
  const packageCount = nodes.filter(n => n.kind === 'package').length

  // Calculate duplicates count and details
  const seenRelations = new Set<string>()
  const duplicateRelationsList: { edge: DiagramRelationDTO; sourceName: string; targetName: string; type: string }[] = []

  edges.forEach(edge => {
    const relType = edge.data?.relationshipType || 'ASSOCIATION'
    const key = `${edge.source}->${edge.target}:${relType}`
    if (seenRelations.has(key)) {
      const srcNode = nodes.find(n => n.id === edge.source)
      const tgtNode = nodes.find(n => n.id === edge.target)
      duplicateRelationsList.push({
        edge,
        sourceName: srcNode?.name || 'Desconocido',
        targetName: tgtNode?.name || 'Desconocido',
        type: relType,
      })
    }
    seenRelations.add(key)
  })

  // Calculate other semantic warnings details
  const relationWarningsList: { edge: DiagramRelationDTO; message: string }[] = []

  edges.forEach(edge => {
    const relType = edge.data?.relationshipType || 'ASSOCIATION'
    const sourceNode = nodes.find(n => n.id === edge.source) as any
    const targetNode = nodes.find(n => n.id === edge.target) as any

    if (!sourceNode || !targetNode) return

    if (isClass) {
      if (relType === 'INHERITANCE' && edge.source === edge.target) {
        relationWarningsList.push({ edge, message: `Clase '${sourceNode.name}' hereda de sí misma.` })
      }
      if (relType === 'IMPLEMENTATION' && targetNode.umlType !== 'INTERFACE') {
        relationWarningsList.push({ edge, message: `Relación '${sourceNode.name} ⊳ ${targetNode.name}' debería apuntar a Interfaz.` })
      }
      if (relType === 'INHERITANCE' && (sourceNode.umlType === 'ENUM' || targetNode.umlType === 'ENUM')) {
        relationWarningsList.push({ edge, message: `Relación '${sourceNode.name} △ ${targetNode.name}' no aplica a enumeraciones.` })
      }
      if (relType === 'COMPOSITION' && targetNode.umlType === 'INTERFACE') {
        relationWarningsList.push({ edge, message: `Composición '${sourceNode.name} ◆ ${targetNode.name}' apunta a una interfaz.` })
      }
    } else {
      const sKind = sourceNode.kind
      const tKind = targetNode.kind
      if (relType === 'ASSOCIATION' && sKind === 'useCase' && tKind === 'useCase') {
        relationWarningsList.push({ edge, message: `Asociación entre casos de uso '${sourceNode.name}' y '${targetNode.name}' puede ser ambigua.` })
      }
      if ((relType === 'INCLUDE' || relType === 'EXTEND') && (sKind === 'actor' || tKind === 'actor')) {
        relationWarningsList.push({ edge, message: `Relación ${relType.toLowerCase()} entre '${sourceNode.name}' y '${targetNode.name}' involucra un actor.` })
      }
      if (relType === 'GENERALIZATION' && sKind !== tKind) {
        relationWarningsList.push({ edge, message: `Generalización '${sourceNode.name} △ ${targetNode.name}' conecta elementos de tipo distinto.` })
      }
    }
  })

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-zinc-950/50 backdrop-blur-sm p-4 animate-in fade-in duration-200 pointer-events-none">
      <div className="w-full max-w-2xl bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-200 pointer-events-auto">
        
        {/* Modal Header */}
        <div className="px-6 py-5 border-b border-zinc-100 dark:border-zinc-900 bg-zinc-50/50 dark:bg-zinc-900/10 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-2xl">📊</span>
            <div>
              <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">
                Calidad y Salud del Diagrama
              </h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400">
                Resumen estructural y sugerencias de diseño UML.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-zinc-100 dark:hover:bg-zinc-900 rounded-xl transition-all text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200"
          >
            ✕
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar text-sm">
          
          {/* Quick Stats Grid */}
          <div className="grid grid-cols-4 gap-4">
            <div className="bg-zinc-50 dark:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800 p-4 rounded-2xl text-center">
              <span className="text-2xl block mb-1">📦</span>
              <span className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase">Nodos</span>
              <span className="text-xl font-bold text-zinc-900 dark:text-zinc-100 block mt-0.5">{nodes.length}</span>
            </div>
            <div className="bg-zinc-50 dark:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800 p-4 rounded-2xl text-center">
              <span className="text-2xl block mb-1">🔗</span>
              <span className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase">Relaciones</span>
              <span className="text-xl font-bold text-zinc-900 dark:text-zinc-100 block mt-0.5">{edges.length}</span>
            </div>
            <div className="bg-zinc-50 dark:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800 p-4 rounded-2xl text-center">
              <span className="text-2xl block mb-1">📁</span>
              <span className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase">Paquetes</span>
              <span className="text-xl font-bold text-zinc-900 dark:text-zinc-100 block mt-0.5">{packageCount}</span>
            </div>
            <div className="bg-zinc-50 dark:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800 p-4 rounded-2xl text-center">
              <span className="text-2xl block mb-1">🤖</span>
              <span className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase">Origen</span>
              <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 block mt-2">
                {isAutoGenerated ? 'Generado por IA' : 'Manual'}
              </span>
            </div>
          </div>

          {/* Quick Actions Panel */}
          <div className="bg-blue-500/5 border border-blue-500/10 p-4 rounded-2xl space-y-3">
            <h4 className="text-xs font-bold text-blue-700 dark:text-blue-400 uppercase tracking-wider">
              Acciones de Optimización Rápida
            </h4>
            <div className="flex gap-2 flex-wrap">
              <Button
                variant="secondary"
                className="text-xs py-1.5 px-3 font-semibold"
                onClick={() => {
                  onAutoLayout()
                  onClose()
                }}
              >
                🪄 Reorganizar automáticamente
              </Button>
              {duplicateRelationsList.length > 0 && (
                <Button
                  variant="destructive"
                  className="text-xs py-1.5 px-3 font-semibold"
                  onClick={() => {
                    onCleanDuplicates()
                    onClose()
                  }}
                >
                  🧹 Limpiar {duplicateRelationsList.length} duplicados
                </Button>
              )}
            </div>
          </div>

          {/* Warnings List */}
          <div className="space-y-4">
            
            {/* 1. Isolated Nodes Section */}
            <div>
              <h4 className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider mb-2">
                Nodos aislados ({isolatedNodes.length})
              </h4>
              {isolatedNodes.length > 0 ? (
                <div className="grid grid-cols-2 gap-2">
                  {isolatedNodes.map(node => (
                    <div 
                      key={node.id} 
                      className="flex items-center justify-between p-2.5 bg-zinc-50 hover:bg-zinc-100 dark:bg-zinc-900/20 dark:hover:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800 rounded-xl transition-all"
                    >
                      <span className="font-semibold text-xs text-zinc-700 dark:text-zinc-300 truncate max-w-[150px]">
                        {node.name}
                      </span>
                      <button
                        onClick={() => onSelectElement('node', node.id)}
                        className="text-[10px] text-blue-500 hover:text-blue-600 font-bold uppercase transition-colors"
                      >
                        Seleccionar
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-zinc-400 dark:text-zinc-500 italic">No hay nodos aislados en el diagrama.</p>
              )}
            </div>

            {/* 2. Duplicate Relations Section */}
            <div>
              <h4 className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider mb-2">
                Relaciones Duplicadas ({duplicateRelationsList.length})
              </h4>
              {duplicateRelationsList.length > 0 ? (
                <div className="space-y-2">
                  {duplicateRelationsList.map((item, idx) => (
                    <div 
                      key={idx} 
                      className="flex items-center justify-between p-3 bg-red-500/5 border border-red-500/10 rounded-xl"
                    >
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-zinc-800 dark:text-zinc-200">
                          {item.sourceName} <span className="text-red-500">→</span> {item.targetName}
                        </p>
                        <p className="text-[10px] text-zinc-400 dark:text-zinc-500 uppercase mt-0.5">
                          Tipo: {item.type}
                        </p>
                      </div>
                      <button
                        onClick={() => onSelectElement('edge', item.edge.id)}
                        className="text-[10px] text-blue-500 hover:text-blue-600 font-bold uppercase transition-colors shrink-0 ml-2"
                      >
                        Seleccionar
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-zinc-400 dark:text-zinc-500 italic">No hay relaciones duplicadas.</p>
              )}
            </div>

            {/* 3. Semantic UML Warnings Section */}
            <div>
              <h4 className="text-xs font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider mb-2">
                Advertencias de Diseño UML ({relationWarningsList.length})
              </h4>
              {relationWarningsList.length > 0 ? (
                <div className="space-y-2">
                  {relationWarningsList.map((item, idx) => (
                    <div 
                      key={idx} 
                      className="flex items-center justify-between p-3 bg-amber-500/5 border border-amber-500/10 rounded-xl"
                    >
                      <p className="text-xs text-amber-800 dark:text-amber-300 flex-1 pr-4">
                        ⚠️ {item.message}
                      </p>
                      <button
                        onClick={() => onSelectElement('edge', item.edge.id)}
                        className="text-[10px] text-blue-500 hover:text-blue-600 font-bold uppercase transition-colors shrink-0"
                      >
                        Seleccionar
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-zinc-400 dark:text-zinc-500 italic">Todo correcto. Tu diseño cumple con el estándar UML.</p>
              )}
            </div>

          </div>

        </div>

        {/* Modal Footer */}
        <div className="px-6 py-4 border-t border-zinc-100 dark:border-zinc-900 bg-zinc-50/50 dark:bg-zinc-900/10 flex justify-between items-center">
          <span className="text-[11px] text-zinc-400 dark:text-zinc-500">
            {lastSavedStatus || 'Estado guardado'}
          </span>
          <Button onClick={onClose} className="px-5 font-bold">
            Entendido
          </Button>
        </div>

      </div>
    </div>
  )
}
