export const endpoints = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
  },
  projects: {
    base: '/api/projects',
    byId: (id: string) => `/api/projects/${id}`,
    byUser: (ownerId: string) => `/api/projects/user/${ownerId}`,
  },
  requirements: {
    base: '/api/requirements',
    convert: '/api/requirements/convert',
    convertBatch: '/api/requirements/convert-batch',
    improve: '/api/requirements/improve',
    memory: (id: string) => `/api/requirements/${id}/memory`,
    deleteImpact: (id: string) => `/api/requirements/${id}/delete-impact`,
    save: '/api/requirements/save',
    byId: (id: string) => `/api/requirements/${id}`,
    byProject: (projectId: string) => `/api/requirements/project/${projectId}`,
    search: '/api/requirements/search',
    duplicates: '/api/requirements/check-duplicates',
    impact: (id: string) => `/api/requirements/${id}/impact`,
    dependency: '/api/requirements/dependency',
    conflicts: (id: string) => `/api/requirements/${id}/conflicts`,
    projectQuality: (projectId: string) => `/api/projects/${projectId}/requirements/quality`,
    quality: (id: string) => `/api/requirements/${id}/quality`,
    reanalyze: (id: string) => `/api/requirements/${id}/quality/reanalyze`,
  },
  validationRules: {
    base: '/api/validation-rules',
    byId: (id: string) => `/api/validation-rules/${id}`,
    byProject: (projectId: string) => `/api/validation-rules/project/${projectId}`,
    toggle: (id: string) => `/api/validation-rules/${id}/toggle`,
    evaluate: '/api/validation-rules/evaluate-requirement',
  },
  diagrams: {
    base: '/api/diagrams',
    manual: '/api/diagrams/manual',
    classAuto: (projectId: string) => `/api/diagrams/class/auto/${projectId}`,
    useCaseManual: '/api/diagrams/use-case/manual',
    useCaseAuto: (projectId: string) => `/api/diagrams/use-case/auto/${projectId}`,
    byId: (diagramId: string) => `/api/diagrams/${diagramId}`,
    byProject: (projectId: string) => `/api/diagrams/project/${projectId}`,
    plantUml: (diagramId: string) => `/api/diagrams/${diagramId}/plantuml`,
    exportPlantUml: (diagramId: string) => `/api/diagrams/${diagramId}/export/puml`,
    exportText: (diagramId: string) => `/api/diagrams/${diagramId}/export/txt`,
    saveRelations: (diagramId: string) => `/api/diagrams/${diagramId}/save-relations`,
  },
  graph: {
    base: '/api/graph',
    impact: (id: string) => `/api/graph/impact/${id}`,
    inferRelations: (projectId: string) => `/api/graph/infer-relations/${projectId}`,
  },
  traceability: {
    base: '/api/traceability-links',
    byRequirement: (id: string) => `/api/requirements/${id}/traceability`,
    byProject: (projectId: string) => `/api/projects/${projectId}/traceability-links`,
    byId: (id: string) => `/api/traceability-links/${id}`,
  },
  testCases: {
    base: '/api/test-cases',
    byProject: (projectId: string) => `/api/test-cases/project/${projectId}`,
    byId: (id: string) => `/api/test-cases/${id}`,
  },
} as const
